on:
  push: {}

name: Build image

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      id: build-image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO:latest build-context -f Dockerfile
        echo "::set-output name=image::ghcr.io/$REPO:latest"
    - name: Log in to GHCR
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      if: github.ref == 'refs/heads/master'
      run: docker push ${{ steps.build.outputs.name }}